const NAKSHATRA = {
    'Ashwini':1,
    'Bharani':2,
    'Krittika':3,
    'Rohini':4,
    'Mrigashira':5,
    'Ardra':6,
    'Punarvasu':7,
    'Pushya':8,
    'Ashlesha':9,
    'Magha':10,
    'Purva Phalguni':11,
    'Uttara Phalguni':12,
    'Hasta':13,
    'Chitra':14,
    'Swati':15,
    'Vishakha':16,
    'Anuradha':17,
    'Jyestha':18,
    'Mula':19,
    'Purva Aashada':20,
    'Uttara Aashada':21,
    'Shravana':22,
    'Dhanishta':23,
    'Shatabhisha':24,
    'Purva Bhadrapada':25,
    'Uttara Bhadrapada':26,
    'Revati':27
}

module.exports = NAKSHATRA